vercel/schemas

deployment/config-static.js, test/test.js, yarn.lock
As per [serve-handler](https://github.com/zeit/serve-handler), I just completed the config for static deployments.
=> Completed static configuration

deployment/config.js, test/deployment.js, yarn.lock
=> Added `limits` to deployment config schema

deployment/config.js, test/deployment.js
Fixes https://github.com/zeit/github-tests/pull/23
=> Validate env types

deployment/config-env.js, test/deployment-env.js
=> Remove reserved env vars

deployment/config.js
=> Add c1-m4086 slot type

deployment/config.js, test/deployment.js
With that, we can make https://github.com/zeit/github-webhook-worker/pull/122 opt-out.
=> Add support for github.autoJobCancelation.

test/user.js, user/index.js
These properties are accepted for `PATCH` when modifying a user document.
=> Add `email` and `platformVersion` to User schema

deployment/config.js, test/deployment.js
In order to address issue https://github.com/zeit/now-cli/issues/1423
=> Make sure scale.min doesn't exceed scale.max

test/user.js, user/index.js
Don't allow dashes at the end of usernames.
=> No dashes at the end of usernames

test/user.js, user/index.js
Allow usernames to start with numeric values.
Related: https://github.com/zeit/api/pull/1108
=> Allow usernames to start with numeric values

test/user.js, user/index.js
https://app.clubhouse.io/vercel/story/16759/refactor-importflowgitnamespace
This PR adds a new field in the schema for the user which stores the id of the Git namespace.
=> Add ImportFlowGitNamespaceId

test/user.js, user/index.js
Extend user schema to support remoteCaching configuration.
=> feat(user): add remoteCaching

test/user.js, user/index.js
Extend user schema to support storing dismissed toasts.
=> feat(user): add dismissedToasts

user/index.js
Related: https://github.com/vercel/schemas/pull/68
=> Fix typo in viewpreference schema

user/index.js
Quick fix
Related: https://github.com/vercel/schemas/pull/68
=> Capitalize constant in user schema

test/user.js, user/index.js
This is an update of the previous PR to match the new work. 
https://github.com/vercel/schemas/pull/67
=> Use arrays for toasts

user/index.js
Adding a setting for User.enablePreviewFeedback, For use with new API endpoint and Preview Comments feature:
https://github.com/vercel/api/pull/13453/files
=> add user enablePreviewFeedback setting

package.json, user/index.js
for https://github.com/vercel/api/pull/14308
=> add User enablePreviewFeedback force values

package.json, test/user.js, user/index.js, yarn.lock
API PR that uses it: https://github.com/vercel/api/pull/18727
=> Add ProjectFavorites to User Schema

package.json, test/user.js, user/index.js
Following pattern set by favorites, adds support for recents view preference
=> [recents] Add recents view preference to user schema

package.json, test/user.js, user/index.js
Limit the allowed characters in the `User.name` field
=> Limit allowed characters in User.name
