deployment/config-static.js

I just noticed a typo. You can find the right config [here](https://github.com/zeit/serve-handler). 💅 
**NOTE:** I personally like "URL" more than "Url", but we want to be compatible with Firebase.

Fixed typo

---

deployment/config-static.js

This allows for https://github.com/zeit/serve-handler/pull/22 to work in Now CLI and `serve`.

Added new `renderSingle` property to static config

---

deployment/config.js
deployment/env.js
test/deployment-env.js
test/deployment.js

The `EnvKeys` and `EnvObject` schemas are the high-level ones.
Note that the consumer will have to validate `EnvKeys` against the `Object.keys(env)` since there does not appear to be a way to "type" the keys of the object in the `EnvObject` schema.

Add `deployment.env` validation

---

deployment/config-env.js
test/deployment-env.js

We need to allow this environment variable to be passed by the user.

Allow `NOW_NPM_TOKEN` env var

---

deployment/config-static.js

The header value can also include these characters, if needed.

Allow more characters in header value

---

deployment/config.js
test/deployment.js

This is required to use with PR: https://github.com/zeit/github-webhook-worker/issues/74
Otherwise `now-cli` throw an error when we trying to deploy the app locally.

Support github.enabled in now.json

---

deployment/config.js
test/deployment.js

This will allow us to opt-out aliasing via GitHub.

Add support for github.aliasing

---

deployment/config.js
test/deployment.js

This flag will stop aliasing automatically on the default branch.

Add github.autoAlias flag to now.json

---

deployment/config.js
test/deployment.js

We don't need this since we've `github.autoAlias`.

Remove support for github.aliasing

---

deployment/config.js
deployment/service.js
test/deployment.js

Will be used to specify an explicit port that the application
is bound to, and the proxy will forward requests to.

Add `service.port` to deployment schema

---

deployment/config.js
test/deployment.js

Support config option for the GitHub silent mode.
If provided, we don't add any comment for deployments. (We only add commit status)

Add silent mode for the GitHub integration.

---

user/index.js

This PR adds the fields needed for public profile pages:
- `bio`
- `website`
- `profiles`
- `publicTeams`

Add public profile fields to user schema

---

user/index.js

We are not using this anymore since we implemented the Custom Suffix so I think we can get rid of it from our schemas.
Closes #31.

Remove default deployment domain

---

deployment/config.js
test/deployment.js

This will allow us to use `project` field in `now.json` for v1 deployments.

Add support for the project field

---

test/user.js
user/index.js

This allows us to use the username directly in domains without the need to modify it.

Don't allow underscores in usernames

---

test/user.js
user/index.js

This PR adds the field `importFlowGitProvider` to the `User` schema. The new field will be used in the new import flow.
https://app.clubhouse.io/vercel/story/4314/create-endpoint-to-edit-preferred-git-connection-used-for-import-flow-suggestions-search

Add importFlowGitProvider to the User schema

---

test/user.js
user/index.js

https://app.clubhouse.io/vercel/story/12414/add-importflowgitnamespace-attribute-to-user-documents
This PR adds a new field on the User's schema which we will use to store the preferred Git Namespace in the Import Flow.

Add importFlowGitNamespace for user

---

test/user.js
user/index.js

In order for new api tests to work
https://github.com/vercel/api/pull/13032
Related to adding a new user preference so the dashboard view preference gets stored

Add ViewPreference to schema

---

package.json
user/index.js

The UI at the team level has three settings and a toggle for allowing projects to override or not.
The previous change here added force-on and force-off, but didn't include a force default, which means that you can toggle the switch to off, but select default and after saving/refreshing the toggle would be changed again.  This change just adds the additional state.

Add an additional flag for default-force setting for feedback

---

deployment/config-static.js
test/deployment.js

- Updates the headers value pattern to support all visible characters from ISO-8859-1, since the current pattern is very restrictive (more information in [RFC9110](https://www.rfc-editor.org/rfc/rfc9110.html#section-5.5-4))
- Adds tests for the above change
Note: The RFC recommends to use only visible US-ASCII octets as values for headers, however, I don't think we should fail the validation for what could be possible as it'll depend on the actual HTTP server to parse that data.

Extend headers validation pattern

---

user/index.js

Extends `User` schema to enable the updating of a user's `defaultTeamId` via the `PATCH` user endpoint in `api`.

feat: add `defaultTeamId` to `User` schema

---

package.json

Tracks changes made in https://github.com/vercel/schemas/pull/81 in order to publish to `npm`.

Bump version to `v2.32.0`

---

package.json
test/user.js
user/index.js

This PR updates the Regex used to validate usernames.
The previous regex did not allow for single character usernames which the file and error message returned to the user said we did.
The previous regex also allowed for usernames that were longer than 48 characters

update username regex
